### ISSUE TITLE
Bugs with duplicate tasks/boards

### ISSUE THREAD

**Issue by Herteby** [czytelny/backlog#1]
If you add two tasks with the same name, they check/uncheck each other when you click them. If you add two boards with the same name, the UI bugs out completely.

Btw, the ability to edit tasks would be nice.

**Comment by czytelny** [comment]
Thanks for taking your time to check it out! I've just fixed bug with same name for item/board and I'm releasing v1.0.1 right now. Newly added tickets/board shouldn't be affected by this issue. Regarding editing task - sure, I'll add it later on, this week perhaps. I'll leave this ticket open to not forget about it :)

**Comment by czytelny** [comment]
fixed in v1.1.0 release
