### ISSUE TITLE
copy/paste

### ISSUE THREAD

**Issue by diomed** [czytelny/backlog#10]
could u integrate copy / paste functionality, perhaps?

**Comment by czytelny** [comment]
On which system you have trouble with copy/paste ? it should be working

**Comment by diomed** [comment]
works with  keyboard shortcuts. 
I'm, I guess used to context menu and right click of the mouse, instead.

**Comment by diomed** [comment]
maybe integration of this package wouldn't be so bad?
https://www.npmjs.com/package/electron-context-menu

**Comment by czytelny** [comment]
I think this app is so simple that adding special context menu just for copy/paste is overkill :)
