### ISSUE TITLE
settings bug?

### ISSUE THREAD

**Issue by diomed** [czytelny/backlog#12]
sometimes when I click on settings nothing really happens. 
doesn't really open them at all.

**Comment by czytelny** [comment]
Which OS ? any more details ? anything specific ? it's hard to say what can cause this, because I never encountered such issue.. and if I can't reproduce it I won't be able to provide any fix

**Comment by diomed** [comment]
it's on Windows 10.

I open it once, and every next time I can't open at all.
It's like it doesn't recognize me clicking on Settings.

**Comment by czytelny** [comment]
I found the issue - when closing modal by clicking outside - it cause problem with re-opening. Will be fixed in v1.4.1 release

**Comment by czytelny** [comment]
fixed in v1.4.1
