### ISSUE TITLE
App Doesn't load -- is blank

### ISSUE THREAD

**Issue by lewri** [czytelny/backlog#24]
Does Backlog require certain permissions to run? Trying to run it from a University managed PC (I'm part of the IT Staff anyway) and the program just comes up blank. When I click on the window the typing cursor appears until I let go.

I'm not able to check if 'run as Administrator' would fix the problem.

Thanks,
![backlog-nothing](https://user-images.githubusercontent.com/20030128/32502875-c6e83432-c3d3-11e7-9ab7-f67a8b08a75a.PNG)

**Comment by czytelny** [comment]
which windows 7/10 are you trying on? and is it x32 or x64 ? is it very old machine?

**Comment by lewri** [comment]
Windows 7 Enterprise x64. Machine is a Stone series (https://www.encore-pc.co.uk/stone-dq67sw-160gb-4gb -- rough model, think ours have more RAM and HDD). Machine is no older than 2013 (think most were bought in 2014).

**Comment by lewri** [comment]
I'm not sure why but I tried another 2 machines this morning and they're both working! I thought it might be because I launched it from a Network Drive but that wasn't the case.

Seems to raise more questions than problems :/

**Comment by czytelny** [comment]
@lewri  can you check latest release 1.4.2 on that one machine where it's not working? I changed npm version and re-run dependency installatio in this releasen, I think that it may be relevant to blank window issue...

**Comment by lewri** [comment]
Was on another machine but It took 4 open/closes before it worked.... After that it was fine.
Really not sure what is happening with it.

We use Electron to run some Kiosks here, which sometimes load blank. I don't know if that could be a related bug to Electron or not.

**Comment by lewri** [comment]
I've been told by someone this could be an issue with Electron, which I will call 'impatience', when loading.
If the application tries to render before all the data is ready it can load blank. A fix on one of our systems here is to introduce a delay to wait for all data to be ready before loading.

However, since I don't know how Backlog works when loading it could be exempt from this issue.

**Comment by czytelny** [comment]
@lewri this should be fixed in v1.6.0 (new Electron version). Can you please check it out ?

**Comment by lewri** [comment]
Sorry for a delay, I was testing 1.61 on Windows 10 x64.
For the most part this is fixed now. It seems like some corrupted appdata from 1.41 was affecting the board from loading anything. After deleting it, it loaded fine.
