### ISSUE TITLE
Feature request: simple confirmation popup when deleting a Board

### ISSUE THREAD

**Issue by imanrp** [czytelny/backlog#3]
I accidentally clicked on the X icon in the tabs and removed a really huge list in an instant. It was a little frustrating and I doubt that I'm the last person that would accidentally do that.

Anyway, I thank you for building this app, Backlog fits my workflow perfectly :)

**Comment by czytelny** [comment]
Thanks for the ticket, absolutely you are right some confirmation dialog is a must-have feature. I'll add it this week perhaps, and release new version. Cool that you like it :)

**Comment by imanrp** [comment]
Great, thank you!

**Comment by diomed** [comment]
there is no undo. that's unfortunate. 
maybe this would be good even for lists - for any kind of click on Remove

**Comment by czytelny** [comment]
@imanrp  confirmation dialog added, new version released (v1.3.3) 
@diomed adding undo action requires a lot of refactoring and perhaps adding vuex to project. right now I dont' have plans related to that feature, maybe in the future

**Comment by diomed** [comment]
ummm.. so - no notifications upon removing item itself?
