### ISSUE TITLE
Doesn't show the boards and the data

### ISSUE THREAD

**Issue by taijidude** [czytelny/backlog#40]
Got a new problem this morning. When i start the app i see my boards and the items for a moment. Than the App doesn't show the boards anymore. Also no config button. 
![backlog_startup_error](https://user-images.githubusercontent.com/24278147/36371863-ac05d174-1563-11e8-90d8-0c78750f4d98.PNG)

**Comment by czytelny** [comment]
sounds not good. re-opening without the effect ? I guess it's some kind of a problem with electron itself. New version will be based on new electron version, hopefully it'll help

**Comment by taijidude** [comment]
I opened it mutiple times, didn't help. Ok, i will look forward to the new version. Thanks a lot for your work.

**Comment by czytelny** [comment]
@taijidude this should be fixed in v1.6.0. Can you please check it out ?

**Comment by taijidude** [comment]
Yes, it works again. Thanks a lot.
