### ISSUE TITLE
Data storage behavior conflict

### ISSUE THREAD

**Issue by mtobeiyf** [czytelny/backlog#47]
Hi, thank you for your nice work :smiley:

![bug1.gif](https://s14.postimg.org/bfkcsy08h/bug1.gif)

When I tried to `npm run dev` on Windows, the data file `backlog.json` isn't modified as expected, as you can see from the above gif.

My guess is that the main process and renderer process both called lowdb and two instances of db exists at the same time. :dancers: When I add a item from rendered process, the json file is modified. However, moving the window calls the storage  function in main process, resulting in the json being overwritten by the previous state that this instance holds in the main process.

When I `npm run build:win32` and run the `exe` directly, same problem occurs.

Strange. Your released version doesn't have this weird problem :)  And I couldn't even find the `backlog.json` file. :joy:
Is my development setting wrong?

**Comment by czytelny** [comment]
Hi, thanks for detailed ticket! Perhaps you're right about two instances of db - I'll investigate and try to fix it. 

Regarding released version - true, it doesn't use `lowdb` at all - it uses different mechanism for storing items and boards. I added it some time ago, but haven't released new version with it yet... good you found it now:)

**Comment by czytelny** [comment]
@mtobeiyf I guess you were right.  I separated window settings (accessed through main process) to another file. This way it doesn't interfere with data from `renderer`. Should be fine now :)
