### ISSUE TITLE
How to properly update?

### ISSUE THREAD

**Issue by diomed** [czytelny/backlog#48]
I'm coming from v 1.4.1
I'm updating like this: 
I deleted Backlog folder within Program files 
and unpacked Backlog from version 1.6 to it's place. 

What happens it basically that I get new version of program, 
but without access to previous data. 
Apparently those migration scrips weren't triggered?

version of Backlog I downloaded is for 64bit Windows.

**Comment by czytelny** [comment]
Hi @diomed, you did everything right - it should be working. 
Check this out :
0. close backlog application
1. go to `%APPDATA%/backlog` in windows explorer. 
2. You should see there files like `backlog.json` and `Settings`. Open them in text editor (eg. notepad)
3. in `backlog.json` new configuration is stored. change line: `"wasImported": true,` into `  "wasImported": false,` - this will force app to re-trigger importing on startup
4. In `Settings` you should be able to see old configuration. You should be able to see there boards in an array and things like eg."board-item-someNumber" (what's interesting for me is that prefix `board-item...`. Can you find such things ?
5. Try to open backlog, it will try to import items again. If not - I'll be thankful for sharing some part of `Settings` file (if you don't have any sensitive data there of course) What you can do is to remove all "text" and "label" occurences before providing me that.

Thanks :)
