### ISSUE TITLE
lost whole board of data

### ISSUE THREAD

**Issue by diomed** [czytelny/backlog#49]
I have to report a bug.

I was entering list of data from a piece of paper, in default board
and suddenly it flashed, like it reloaded or smth. and board went blank
like I entered nothing at all. 
Tried closing and opening, didn't help.
Doesn't backlog have some kind of autosave , or in-memory storage,
so one could retrieve such data loss? if not, maybe it should?

**Comment by diomed** [comment]
yeah, I don't get it. for some reason I'm sometimes still losing new data. 😞

**Comment by czytelny** [comment]
@diomed I found and reproduced similar bug - it was related to 'settings' modal window. Should be fixed in next release. Now the question is: can you recall what exactly have you done just before data lost ? maybe you used 'settings' modal?

**Comment by diomed** [comment]
yes, most likely that was it.

**Comment by czytelny** [comment]
should be fixed in v1.7.0
