### ISSUE TITLE
json list maker?

### ISSUE THREAD

**Issue by diomed** [czytelny/backlog#5]
what do you think about expanding this into json list maker app? [in separate repo?]

where boards would be **objects** 
and lists would be 2 columned 
with **strings** on the left & **values** on the right.

and anyone could so simple **write and export json** in a breeze,
not worrying about syntax because app would do that for user.

**Comment by czytelny** [comment]
sure, I think it's a cool idea for new project! :) feel free to implement it

**Comment by diomed** [comment]
I meant - could you do it, perhaps?
I don't have enough vue knowledge yet to do it.
(just a beginner)
