### ISSUE TITLE
settings modal

### ISSUE THREAD

**Issue by diomed** [czytelny/backlog#55]
First of all - thanks very much for new update, I'm trying it already 👍 

I was wondering, could you maybe make settings modal to close when 
one clicks on overlay behind it, for next version? (and maybe on ESC as well)

That's the only thing that bugs me, really. 
Everything else is pretty much perfect in it's simplicity.

**Comment by czytelny** [comment]
sure, not a problem. will add in next release

**Comment by czytelny** [comment]
should be fixed in 1.8.0
