### ISSUE TITLE
Vue Devtool shows so many components.

### ISSUE THREAD

**Issue by shirshak55** [czytelny/backlog#56]
Is this normal?
<img width="944" alt="screen shot 2018-07-09 at 6 25 07 pm" src="https://user-images.githubusercontent.com/8097377/42450939-7ef703e6-83a5-11e8-87ab-f15404a3792a.png">

**Comment by czytelny** [comment]
Hi, it's good question.. I don't know why you see so many Root components. On my dev env it looks like this: 
![image](https://user-images.githubusercontent.com/5399256/42589431-3744e32c-8541-11e8-8175-9e439a88bbde.png)

**Comment by bloggervista** [comment]
May be its cross platform issue. I am doing this on mac. If I open that root component it will be shown. May be something is wrong :) If I find the error will report you :)

Thank You
