### ISSUE TITLE
scrollbar

### ISSUE THREAD

**Issue by diomed** [czytelny/backlog#59]
is this scrollbar such as browser scrollbar - if it is, can we maybe style it on our end?

or add mby smth like this: https://github.serafin.io/vuebar/

**Comment by czytelny** [comment]
Currently scrollbar is mess (not only it's UI but also behaviour). On MacOS it looks fine, but windows/linux is bad - it's visible all the time, overlap content etc.. I'm going to redesign it, but it's going to be bigger task. Thanks for reference, maybe something like this appear at the end

**Comment by czytelny** [comment]
@diomed  I just uploaded [v1.8.0](https://github.com/czytelny/backlog/releases/tag/v1.8.0) with huge number of improvements. Can you take a look if it's working as expected ? (Links on main page are deliberately not yet altered to point to new version)

**Comment by diomed** [comment]
![screenshot_11](https://user-images.githubusercontent.com/72777/43926859-d719aa58-9c2b-11e8-9b1f-8bcbec421f08.png)

It's working really good, Thank You very much for this update 👍 

There is one minor bug, as you can see on image above, sometimes when I click on tab, list slides, 
from right to left, and it seems like it slides too much (all the way) - so content isn't visible at all.
That is instantly fixed upon reload, yet, still, it happens, so that would be worth fixing in next release.

Search should look for all items in backlog, or be configured in settings to search for items in board /  all items.

That is all I could think of. Thank You once again ☑️

**Comment by czytelny** [comment]
Thanks! Good it's working, because it was huge rewrite (to Vuex). This issue with sliding is not so minor bug and what's worst I don't really know how to fix it. because it's handled by iView... I need to think out something.
