### ISSUE TITLE
scroll through tabs

### ISSUE THREAD

**Issue by diomed** [czytelny/backlog#6]
would it be possible for program to have option to scroll through tabs,
when it is minimized it has more tabs than one can see, than when it's 
fully maximized. this would also allow us to have more data stored in sections.

**Comment by czytelny** [comment]
good point, although i need to consider how to do it :)

**Comment by diomed** [comment]
I wonder would some of this help you: 
https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent


https://github.com/nurupo/chrome-mouse-wheel-tab-scroller

**Comment by czytelny** [comment]
fixed in v1.4.1
