### ISSUE TITLE
Issue when sliding tabs

### ISSUE THREAD

**Issue by czytelny** [czytelny/backlog#61]
sometimes when user switch between tabs view scroll too much sometimes. Happens especially when user has many items/boards and/or slow cpu

**Comment by diomed** [comment]
I hope 2.0 will fix this unlucky bug

**Comment by czytelny** [comment]
@diomed can you ping me on email (my github account name on gmail) ? Although it's not ready for release yet (number of features are not ready yet) I'd love to hear your opinion about alpha version of backlog 2.0

**Comment by diomed** [comment]
I just sent you a hello :)

**Comment by czytelny** [comment]
fixed in 2.0.0 beta
