### ISSUE TITLE
pls disable opening of links

### ISSUE THREAD

**Issue by diomed** [czytelny/backlog#62]
this app acts like browser, when I click on link, 
instead of opening link in browser it opens it in itself.

that's not really wanted behavior.
links should open in browser only.

**Comment by diomed** [comment]
wouldn't mind tho if there was some sort of tooltip system implemented so we could see image /page loaded that way.

**Comment by czytelny** [comment]
@diomed where exactly can you observe this issue ? When I'm trying to click a link - it opens in a regular system browser - not in the app

**Comment by diomed** [comment]
links that are wrapped in markdown open in application itself.

If I have it like `[Pastecloud](http://pastecloud.net)` it'll open in application

**Comment by czytelny** [comment]
fixed in 2.0.0 beta
