### ISSUE TITLE
like

### ISSUE THREAD

**Issue by diomed** [czytelny/backlog#63]
what do you think of liking system?

it's just a thought, but worth mentioning.

maby to put ❤️ icon next to edit button, on the right side. 
could be toggled to display per wish.

**Comment by czytelny** [comment]
I'm working on 2.0.0 version now and considering different approaches (likes/tags/priorityes etc.) I'll let you know once beta is ready to see how things looks like and work

**Comment by czytelny** [comment]
due to adding emoji, this won't be implemented
