### ISSUE TITLE
viewport height

### ISSUE THREAD

**Issue by diomed** [czytelny/backlog#64]
looks like each tab height is set to be as big as the biggest list.
can that not be so?

because when list is short scrollbar still scrolls and ends on lots of unnecesary blank space, I think.

**Comment by czytelny** [comment]
It's a design related bug which cannot be easily fixed in current approach. This will be addressed in 2.x, though. Stay tuned :)

**Comment by czytelny** [comment]
fixed in 2.0.0 beta
