### ISSUE TITLE
Save board as a JSON on macOS

### ISSUE THREAD

**Issue by zinwalin** [czytelny/backlog#67]
Click "Save as a JSON" in settings under 'Setup board names and order', then click 'Cancel' on pop-up window, backlog shows errors as follows:

 **Could not call remote function ''. Check that the function signature is correct. Underlying error: path must be a string or Buffer Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: path must be a string or Buffer at callFunction (/Users/xxx/Development/backlog/build/Backlog-darwin-x64/Backlog.app/Contents/Resources/electron.asar/browser/rpc-server.js:257:11) at EventEmitter. (/Users/xxx/Development/backlog/build/Backlog-darwin-x64/Backlog.app/Contents/Resources/electron.asar/browser/rpc-server.js:357:5) at emitMany (events.js:147:13) at EventEmitter.emit (events.js:224:7) at WebContents. (/Users/xxx/Development/backlog/build/Backlog-darwin-x64/Backlog.app/Contents/Resources/electron.asar/browser/api/web-contents.js:295:13) at emitTwo (events.js:126:13) at WebContents.emit (events.js:214:7)**

can't dismiss error dialog, it's annoying.

**Comment by czytelny** [comment]
some more details here? looks like some problem with destination path.
