### ISSUE TITLE
Using standard navigation keys for boards navigation

### ISSUE THREAD

**Issue by SR-G** [czytelny/backlog#69]
I'm really struggling with the shortcuts currently defined for boards navigation (having a french keyboard).
Is this customizable ?
Or is it possible to add by default very standard shortcuts like CTRL + PAGE_UP / CTRL + PAGE DOWN or CTRL + TAB / CTRL + SHIFT + TAB ?

**Comment by czytelny** [comment]
Hey, 2.0 version keybindings will be fully customisable, it should be solved then.

**Comment by czytelny** [comment]
@SR-G you can check out beta version and see if assigning custom keys works for you now: http://backlog.cloud/beta/

**Comment by SR-G** [comment]
I can confirm that custom key bindings for switching between boards is working.

But i found that a few key bindings are missing, for example (as i'm used to work a lot through keyboards and as rarely as possible with the mouse), when editing an item, a keymap to validate the input area (for example, CTRL+ENTER) and one to cancel it (for example, ESC) would be nice.

**Comment by czytelny** [comment]
I'll add it right away. Anything else is missing in terms of keyboard usability?

**Comment by SR-G** [comment]
No as far as i can tell, that should be fine for now on my side. Thanks.

**Comment by czytelny** [comment]
New beta-3 release includes accept/cancel editing item shortcuts 👍 hope you like it :)

**Comment by czytelny** [comment]
fixed in 2.0.0 Beta
