### ISSUE TITLE
Option to duplicate a task list

### ISSUE THREAD

**Issue by Imerion** [czytelny/backlog#71]
Hi! I recently found this great program which almost fits my needs perfectly. What would make the app perfect would be a way of creating a "template"-list that can be duplicated for projects that usually have the same items. So I can create a normal list (that I use as a template) and then just duplicate it to have a new tab with a new list that I can start ticking things off from. Would something like that be possible to add? Perhaps simply by right-clicking on a tab and choosing a "Duplicate" option?

**Comment by czytelny** [comment]
Hi there, thanks for comment. Definitely it sound like a good idea! 👍 I'll add it to 2.0.0 version which I'm working on right now. I'll let you know once I release beta version with this feature so you can check it out ;)

**Comment by czytelny** [comment]
@Imerion I added duplicate board feature in new Beta release. You can check this out and see if it works for you: http://www.backlog.cloud/beta/

**Comment by Imerion** [comment]
Fantastic! Thanks for adding that! Will try the beta as soon as I have access to a Windows machine. (I run Linux on the ones I usually use.)

**Comment by Imerion** [comment]
Thanks again! Tried it and it works perfectly! Emoji work great here too, using Xubuntu 18.10.
