### ISSUE TITLE
Feature request: Choose storage location

### ISSUE THREAD

**Issue by TobiasDev** [czytelny/backlog#73]
I've seen that it says in the app where it stores all the data. Would it be possible to change this so I can set myself where I want to store my data? Because that way I could have it synced between my different PC's by just choosing to store the data in my NextCloud folder.

**Comment by czytelny** [comment]
hi, it duplicates #31. Unfortunately it won't be implemented fast due to complexity of this task. 
Right now I'm working on cloud integration which will allow to share data between different PCs
