### ISSUE TITLE
cloud.js not found

### ISSUE THREAD

**Issue by znlnzi** [czytelny/backlog#78]
Backlog version: 2.0.4-beta
These relative modules were not found:
* ./../cloud in ./src/repositories/syncRepository.js
* ./cloud in ./src/cloudMixin.js

**Comment by Tebra** [comment]
+1 
Just wanted to write an issue now but you beat me to it! :)

**Comment by czytelny** [comment]
hi, sorry, forget to commit :) should be fine now.
