### ISSUE TITLE
More Lists

### ISSUE THREAD

**Issue by taijidude** [czytelny/backlog#8]
Hello, 

startet using Backog last week. Really like it. The only thing that bothers me a little is, that i can only create 5 Lists. After that the plus item deactivates. I would be great to have more lists. Thank you. 

Patrick

**Comment by czytelny** [comment]
Hi, no problem, I'll drop out this limit in next release (hopefull this week)

**Comment by taijidude** [comment]
Awesome! Thanks a lot.

**Comment by czytelny** [comment]
Took me little bit longer than one week, but it's done finally :)
