### ISSUE TITLE
search

### ISSUE THREAD

**Issue by diomed** [czytelny/backlog#82]
I'd like better access to search.

Maybe a big search icon on the left area where the boards are

**Comment by czytelny** [comment]
Hi, are you commenting Beta version? There is already "find item button" on the left menu area. Isn't it visible enough?

**Comment by diomed** [comment]
yeah. it isn't. 


it also isn't classical magnifier icon, so it's a bit confusing.

Would be great if there was double sized magnifying icon on left area where boards are. 
[below them]

or somewhere else, IDK

**Comment by diomed** [comment]
would you also add tiny blue or green visible icon right from filter

**Comment by czytelny** [comment]
Thanks, will work on icons visibility
