### ISSUE TITLE
**DON'T ALLOW** same name of boards!

### ISSUE THREAD

**Issue by diomed** [czytelny/backlog#89]
It shouldn't be allowed to have same names of boards;
like if I wanted to create 10 boards named Stories - 

instead, boards should have names such as 

Stories 02
Stories 03

etc.
or something similar.

**Comment by czytelny** [comment]
I don't want to alter user input or put artificial limits. If somebody doesn't want to have two boards with the same name simply rename one of it :)

**Comment by diomed** [comment]
board names shouldn't be the same, because they're like categories.
and what I did today was - I tried to create a board, but because of lag,
in the end I ended up with up to 15 boards with the same name, which 
I had to delete manually. if only there was a way to stop me from doing that
automatically. - maybe at least ask a permission from user if he really wants to do that.
