### ISSUE TITLE
Deletion/ADDING / Renaming of boards AND ITEMS bug [something's off!!!]

### ISSUE THREAD

**Issue by diomed** [czytelny/backlog#90]
User should be able to select YES, REMOVE IT - via keyboard, when deleting board.
Currently, I'm unable to do that.

Also - there is a **bug**, deleting a board doesn't autoupdate in preview.
I only see board is deleted when I restart program.

**Comment by diomed** [comment]
also, renaming doesn't work - doesn't autoupdate, but only on restart it's shown I changed something

**Comment by diomed** [comment]
ps - this could all be my fault, coz ATM I'm running on 128MB of storage....

so yeah.... 
if it works for you, please ignore and close this one.
sorry.

**Comment by diomed** [comment]
ok, I'm having problems with adding items as well. auto-refresh simply doesn't work, and nothing displays in real time until one restarts.

will switch to previous version until problem is solved.

**Comment by czytelny** [comment]
Seems like one problem which broke all functionalities. Any details ? What exactly steps are taken to produce wrong behaviour? Can't reproduce an error

**Comment by diomed** [comment]
unsure what steps are taken. and what should I safely delete or not...
I guess I'll just switch to old one until final v. is out. 🤔

**Comment by czytelny** [comment]
The problem is that final version will contain exactly the same problem if I won't explicitly fix it :) And I won't be able to fix it if I can't find the reason and reproduce it. 
You should be able to safely delete everything and add everything. If you open Beta-5 and try to add something (board/item) - is it working as expected? or it's broken from start?

**Comment by diomed** [comment]
let me delete it and then reinstall it, maybe it's just some installation glitch

**Comment by diomed** [comment]
nope. I reinstalled, and it's happening again. don't know what's up.
every time I write something it wont autoupdate, and input bar where I enter words
simply disappears from view, fades down, and program becomes unusable for adding 
another item

**Comment by czytelny** [comment]
is it happening on all boards, or only some particular ? after re-running app is this item visible on the board ?

**Comment by diomed** [comment]
after I enter item on one board, I cannot enter item on any board at all.
input box disappears.

after re-running app item is visible in the board.
and one which is deleted, is deleted from the board.

it just doesnt autoupdate when app is running.

**Comment by diomed** [comment]
any luck in figuring out this?

**Comment by czytelny** [comment]
Yes, found an error, I'll prepare Beta 5.1 soon

**Comment by diomed** [comment]
super cool. can you chat a bit?
https://tlk.io/backlog

**Comment by czytelny** [comment]
Version 5.1 released for Mac and Windows, it should fix this bug, please retest:
https://github.com/czytelny/backlog/releases/tag/v2.0.0-Beta-5.1
Added also Croatian language with your translation 👍
